stages:
  - deploy

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - cd /opt/pochacco
    - git pull origin main
    - docker compose up -d --build
    - echo "Deploy completed at $(date)"
  tags:
    - pochacco-server
  environment:
    name: production
    url: http://120.24.223.14
